module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.21.10

replace github.com/korrel8r/korrel8r/client => ./client

exclude k8s.io/client-go v12.0.0+incompatible

require github.com/korrel8r/korrel8r v0.6.4 // cmd/korrel8r
