// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Class Full name of a class of data, format is DOMAIN:CLASS. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name within the domain.
type Class = string

// Console State of the user's graphical console display (e.g. OpenShift web console).
type Console struct {
	// Search The troubleshooting panel displays the results of this correlation search.
	Search *Search `json:"search,omitempty" jsonschema:"The troubleshooting panel displays the results of this correlation search."`

	// View The main console view displays the results of this query.
	View Query `json:"view,omitempty" jsonschema:"Query for the main console view, in DOMAIN:CLASS:SELECTOR format."`
}

// Constraint Constrains the objects that will be included in search results.
type Constraint struct {
	// End Ignore objects with timestamps after this end time.
	End *time.Time `json:"end,omitempty" jsonschema:"Ignore objects with timestamps after this end time."`

	// Limit Limit total number of objects per query.
	Limit *int `json:"limit,omitempty" jsonschema:"Limit total number of objects per query."`

	// Start Ignore objects with timestamps before this start time.
	Start *time.Time `json:"start,omitempty" jsonschema:"Ignore objects with timestamps before this start time."`
}

// Domain Domain configuration information.
type Domain struct {
	// Description Brief description of the domain.
	Description string `json:"description,omitempty"`

	// Name Name of the domain.
	Name string `json:"name"`

	// Stores Stores configured for the domain.
	Stores []Store `json:"stores,omitempty"`
}

// Edge Directed edge in the result graph, from Start to Goal classes.
type Edge struct {
	// Goal Class name of the goal node.
	Goal Class `json:"goal" jsonschema:"Class name of the goal node, in DOMAIN:CLASS format."`

	// Rules Set of rules followed along this edge.
	Rules []Rule `json:"rules,omitempty" jsonschema:"Set of rules followed along this edge."`

	// Start Class name of the start node.
	Start Class `json:"start" jsonschema:"Class name of the start node, in DOMAIN:CLASS format."`
}

// Error Error result containing an error message.
type Error struct {
	// Error Error message.
	Error string `json:"error"`
}

// Goals Parameters for a goal-directed correlation search. Finds paths from start objects to goal classes.
type Goals struct {
	// Goals Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert
	Goals []Class `json:"goals" jsonschema:"Goal classes in DOMAIN:CLASS format, e.g. log:application, alert:alert."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Graph Graph resulting from a correlation search.
type Graph struct {
	// Edges List of graph edges.
	Edges []Edge `json:"edges,omitempty" jsonschema:"List of graph edges."`

	// Nodes List of graph nodes.
	Nodes []Node `json:"nodes,omitempty" jsonschema:"List of graph nodes."`
}

// Neighbors Parameters for a neighborhood correlation search. Finds all objects reachable from the start by following correlation rules up to the maximum depth.
type Neighbors struct {
	// Depth Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only.
	Depth int `json:"depth" jsonschema:"Maximum number of correlation steps to follow from the start. Depth 1 returns direct correlations only."`

	// Start Starting point for the search.
	Start Start `json:"start" jsonschema:"Starting point for the search."`
}

// Node Node in the result graph, contains results for a single class.
type Node struct {
	// Class Full class name.
	Class string `json:"class" jsonschema:"Full class name in DOMAIN:CLASS format."`

	// Count Number of results for this class, after de-duplication.
	Count *int `json:"count,omitempty" jsonschema:"Number of results for this class, after de-duplication."`

	// Queries Queries yielding results for this class.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries yielding results for this class."`

	// Result Serialized result contents, may be large.
	Result []Object `json:"result,omitempty" jsonschema:"Serialized result contents, may be large."`
}

// Object Data object serialized as JSON.
type Object = json.RawMessage

// Query Query for data objects, format is DOMAIN:CLASS:SELECTOR. DOMAIN: name of a domain (e.g. k8s, log, metric, alert, trace, netflow). CLASS: name of a class in the domain (e.g. Pod, application, metric, alert, span, network). SELECTOR: domain-specific query string.
type Query = string

// QueryCount Query with number of results.
type QueryCount struct {
	// Count Number of results, omitted if the query was not executed.
	Count *int `json:"count,omitempty" jsonschema:"Number of results, omitted if the query was not executed."`

	// Query Query for correlation data.
	Query Query `json:"query" jsonschema:"Query for correlation data in DOMAIN:CLASS:SELECTOR format."`
}

// Rule Rule is a correlation rule with a list of queries and results counts found during navigation.
type Rule struct {
	// Name Name is an optional descriptive name.
	Name string `json:"name" jsonschema:"Name is an optional descriptive name."`

	// Queries Queries generated while following this rule.
	Queries []QueryCount `json:"queries,omitempty" jsonschema:"Queries generated while following this rule."`
}

// Search Correlation search parameters. Set exactly one of 'goals' (targeted search to specific classes) or 'neighbors' (open-ended exploration to a depth).
type Search struct {
	// Goals Parameters for a goal-directed correlation search.
	Goals *Goals `json:"goals,omitempty" jsonschema:"Parameters for a goal-directed correlation search."`

	// Neighbors Parameters for a neighborhood correlation search.
	Neighbors *Neighbors `json:"neighbors,omitempty" jsonschema:"Parameters for a neighborhood correlation search."`
}

// Start Starting point for a correlation search. It usually specifies queries to get the starting objects, but can include serialized objects as well as/instead of queries.
type Start struct {
	// Class Class of starting objects. Required when using 'objects' to provide serialized objects. If queries are included, they must all be of this class.
	Class Class `json:"class,omitempty" jsonschema:"Class of starting objects in DOMAIN:CLASS format. Required when using objects. If queries are included, they must all be of this class."`

	// Constraint Constrains the objects that will be included in search results.
	Constraint *Constraint `json:"constraint,omitempty" jsonschema:"Constrains the objects that will be included in search results."`

	// Objects Start objects serialized as JSON. Requires 'class' to identify the object type. Alternative to 'queries' when you already have the objects.
	Objects []Object `json:"objects,omitempty" jsonschema:"Start objects serialized as JSON. Requires class to identify the object type."`

	// Queries Queries for starting objects in "domain:class:selector" format. This is the most common way to specify a starting point.
	Queries []Query `json:"queries,omitempty" jsonschema:"Queries for starting objects in DOMAIN:CLASS:SELECTOR format."`
}

// Store Store is a map string keys and values used to connect to a store.
type Store map[string]string

// GraphOptions Options controlling the form of the returned graph.
type GraphOptions struct {
	// Errors If true include non-fatal error messages.
	Errors *bool `json:"errors,omitempty" jsonschema:"If true include non-fatal error messages."`

	// Results If true include full JSON results with each Query.
	Results *bool `json:"results,omitempty" jsonschema:"If true include full JSON results with each Query."`

	// Rules If true include rule names in graph edges.
	Rules *bool `json:"rules,omitempty" jsonschema:"If true include rule names in graph edges."`
}

// SetConfigParams defines parameters for SetConfig.
type SetConfigParams struct {
	// Verbose Verbose level for logging.
	Verbose *int `form:"verbose,omitempty" json:"verbose,omitempty"`
}

// GraphGoalsParams defines parameters for GraphGoals.
type GraphGoalsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighborsParams defines parameters for GraphNeighbors.
type GraphNeighborsParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// GraphNeighboursParams defines parameters for GraphNeighbours.
type GraphNeighboursParams struct {
	// Options Options controlling the form of the returned graph.
	Options *GraphOptions `form:"options,omitempty" json:"options,omitempty"`
}

// ObjectsParams defines parameters for Objects.
type ObjectsParams struct {
	// Query Query string.
	Query Query `form:"query" json:"query"`
}

// SetConsoleJSONRequestBody defines body for SetConsole for application/json ContentType.
type SetConsoleJSONRequestBody = Console

// GraphGoalsJSONRequestBody defines body for GraphGoals for application/json ContentType.
type GraphGoalsJSONRequestBody = Goals

// GraphNeighborsJSONRequestBody defines body for GraphNeighbors for application/json ContentType.
type GraphNeighborsJSONRequestBody = Neighbors

// GraphNeighboursJSONRequestBody defines body for GraphNeighbours for application/json ContentType.
type GraphNeighboursJSONRequestBody = Neighbors

// ListGoalsJSONRequestBody defines body for ListGoals for application/json ContentType.
type ListGoalsJSONRequestBody = Goals

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SetConfig request
	SetConfig(ctx context.Context, params *SetConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetConsoleWithBody request with any body
	SetConsoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SetConsole(ctx context.Context, body SetConsoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConsoleEvents request
	ConsoleEvents(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDomainClasses request
	ListDomainClasses(ctx context.Context, domain string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDomains request
	ListDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GraphGoalsWithBody request with any body
	GraphGoalsWithBody(ctx context.Context, params *GraphGoalsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GraphGoals(ctx context.Context, params *GraphGoalsParams, body GraphGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GraphNeighborsWithBody request with any body
	GraphNeighborsWithBody(ctx context.Context, params *GraphNeighborsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GraphNeighbors(ctx context.Context, params *GraphNeighborsParams, body GraphNeighborsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GraphNeighboursWithBody request with any body
	GraphNeighboursWithBody(ctx context.Context, params *GraphNeighboursParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	GraphNeighbours(ctx context.Context, params *GraphNeighboursParams, body GraphNeighboursJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListGoalsWithBody request with any body
	ListGoalsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ListGoals(ctx context.Context, body ListGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Objects request
	Objects(ctx context.Context, params *ObjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SetConfig(ctx context.Context, params *SetConfigParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetConfigRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetConsoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetConsoleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SetConsole(ctx context.Context, body SetConsoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetConsoleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ConsoleEvents(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConsoleEventsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDomainClasses(ctx context.Context, domain string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDomainClassesRequest(c.Server, domain)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDomainsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GraphGoalsWithBody(ctx context.Context, params *GraphGoalsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGraphGoalsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GraphGoals(ctx context.Context, params *GraphGoalsParams, body GraphGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGraphGoalsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GraphNeighborsWithBody(ctx context.Context, params *GraphNeighborsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGraphNeighborsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GraphNeighbors(ctx context.Context, params *GraphNeighborsParams, body GraphNeighborsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGraphNeighborsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GraphNeighboursWithBody(ctx context.Context, params *GraphNeighboursParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGraphNeighboursRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GraphNeighbours(ctx context.Context, params *GraphNeighboursParams, body GraphNeighboursJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGraphNeighboursRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListGoalsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListGoalsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListGoals(ctx context.Context, body ListGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListGoalsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Objects(ctx context.Context, params *ObjectsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewObjectsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSetConfigRequest generates requests for SetConfig
func NewSetConfigRequest(server string, params *SetConfigParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Verbose != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "verbose", *params.Verbose, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetConsoleRequest calls the generic SetConsole builder with application/json body
func NewSetConsoleRequest(server string, body SetConsoleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetConsoleRequestWithBody(server, "application/json", bodyReader)
}

// NewSetConsoleRequestWithBody generates requests for SetConsole with any type of body
func NewSetConsoleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/console")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewConsoleEventsRequest generates requests for ConsoleEvents
func NewConsoleEventsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/console/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDomainClassesRequest generates requests for ListDomainClasses
func NewListDomainClassesRequest(server string, domain string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domain", domain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domain/%s/classes", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDomainsRequest generates requests for ListDomains
func NewListDomainsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGraphGoalsRequest calls the generic GraphGoals builder with application/json body
func NewGraphGoalsRequest(server string, params *GraphGoalsParams, body GraphGoalsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGraphGoalsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewGraphGoalsRequestWithBody generates requests for GraphGoals with any type of body
func NewGraphGoalsRequestWithBody(server string, params *GraphGoalsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/graphs/goals")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Options != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "options", *params.Options, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGraphNeighborsRequest calls the generic GraphNeighbors builder with application/json body
func NewGraphNeighborsRequest(server string, params *GraphNeighborsParams, body GraphNeighborsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGraphNeighborsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewGraphNeighborsRequestWithBody generates requests for GraphNeighbors with any type of body
func NewGraphNeighborsRequestWithBody(server string, params *GraphNeighborsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/graphs/neighbors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Options != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "options", *params.Options, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGraphNeighboursRequest calls the generic GraphNeighbours builder with application/json body
func NewGraphNeighboursRequest(server string, params *GraphNeighboursParams, body GraphNeighboursJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewGraphNeighboursRequestWithBody(server, params, "application/json", bodyReader)
}

// NewGraphNeighboursRequestWithBody generates requests for GraphNeighbours with any type of body
func NewGraphNeighboursRequestWithBody(server string, params *GraphNeighboursParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/graphs/neighbours")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Options != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "options", *params.Options, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListGoalsRequest calls the generic ListGoals builder with application/json body
func NewListGoalsRequest(server string, body ListGoalsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewListGoalsRequestWithBody(server, "application/json", bodyReader)
}

// NewListGoalsRequestWithBody generates requests for ListGoals with any type of body
func NewListGoalsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/lists/goals")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewObjectsRequest generates requests for Objects
func NewObjectsRequest(server string, params *ObjectsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/objects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "query", params.Query, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SetConfigWithResponse request
	SetConfigWithResponse(ctx context.Context, params *SetConfigParams, reqEditors ...RequestEditorFn) (*SetConfigResponse, error)

	// SetConsoleWithBodyWithResponse request with any body
	SetConsoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetConsoleResponse, error)

	SetConsoleWithResponse(ctx context.Context, body SetConsoleJSONRequestBody, reqEditors ...RequestEditorFn) (*SetConsoleResponse, error)

	// ConsoleEventsWithResponse request
	ConsoleEventsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ConsoleEventsResponse, error)

	// ListDomainClassesWithResponse request
	ListDomainClassesWithResponse(ctx context.Context, domain string, reqEditors ...RequestEditorFn) (*ListDomainClassesResponse, error)

	// ListDomainsWithResponse request
	ListDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDomainsResponse, error)

	// GraphGoalsWithBodyWithResponse request with any body
	GraphGoalsWithBodyWithResponse(ctx context.Context, params *GraphGoalsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GraphGoalsResponse, error)

	GraphGoalsWithResponse(ctx context.Context, params *GraphGoalsParams, body GraphGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*GraphGoalsResponse, error)

	// GraphNeighborsWithBodyWithResponse request with any body
	GraphNeighborsWithBodyWithResponse(ctx context.Context, params *GraphNeighborsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GraphNeighborsResponse, error)

	GraphNeighborsWithResponse(ctx context.Context, params *GraphNeighborsParams, body GraphNeighborsJSONRequestBody, reqEditors ...RequestEditorFn) (*GraphNeighborsResponse, error)

	// GraphNeighboursWithBodyWithResponse request with any body
	GraphNeighboursWithBodyWithResponse(ctx context.Context, params *GraphNeighboursParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GraphNeighboursResponse, error)

	GraphNeighboursWithResponse(ctx context.Context, params *GraphNeighboursParams, body GraphNeighboursJSONRequestBody, reqEditors ...RequestEditorFn) (*GraphNeighboursResponse, error)

	// ListGoalsWithBodyWithResponse request with any body
	ListGoalsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListGoalsResponse, error)

	ListGoalsWithResponse(ctx context.Context, body ListGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListGoalsResponse, error)

	// ObjectsWithResponse request
	ObjectsWithResponse(ctx context.Context, params *ObjectsParams, reqEditors ...RequestEditorFn) (*ObjectsResponse, error)
}

type SetConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r SetConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SetConsoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r SetConsoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetConsoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ConsoleEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ConsoleEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConsoleEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDomainClassesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]string
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ListDomainClassesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDomainClassesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Domain
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ListDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GraphGoalsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Graph
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GraphGoalsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GraphGoalsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GraphNeighborsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Graph
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GraphNeighborsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GraphNeighborsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GraphNeighboursResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Graph
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GraphNeighboursResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GraphNeighboursResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListGoalsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Node
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ListGoalsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListGoalsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ObjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]map[string]interface{}
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ObjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ObjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SetConfigWithResponse request returning *SetConfigResponse
func (c *ClientWithResponses) SetConfigWithResponse(ctx context.Context, params *SetConfigParams, reqEditors ...RequestEditorFn) (*SetConfigResponse, error) {
	rsp, err := c.SetConfig(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetConfigResponse(rsp)
}

// SetConsoleWithBodyWithResponse request with arbitrary body returning *SetConsoleResponse
func (c *ClientWithResponses) SetConsoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetConsoleResponse, error) {
	rsp, err := c.SetConsoleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetConsoleResponse(rsp)
}

func (c *ClientWithResponses) SetConsoleWithResponse(ctx context.Context, body SetConsoleJSONRequestBody, reqEditors ...RequestEditorFn) (*SetConsoleResponse, error) {
	rsp, err := c.SetConsole(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetConsoleResponse(rsp)
}

// ConsoleEventsWithResponse request returning *ConsoleEventsResponse
func (c *ClientWithResponses) ConsoleEventsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ConsoleEventsResponse, error) {
	rsp, err := c.ConsoleEvents(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConsoleEventsResponse(rsp)
}

// ListDomainClassesWithResponse request returning *ListDomainClassesResponse
func (c *ClientWithResponses) ListDomainClassesWithResponse(ctx context.Context, domain string, reqEditors ...RequestEditorFn) (*ListDomainClassesResponse, error) {
	rsp, err := c.ListDomainClasses(ctx, domain, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDomainClassesResponse(rsp)
}

// ListDomainsWithResponse request returning *ListDomainsResponse
func (c *ClientWithResponses) ListDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDomainsResponse, error) {
	rsp, err := c.ListDomains(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDomainsResponse(rsp)
}

// GraphGoalsWithBodyWithResponse request with arbitrary body returning *GraphGoalsResponse
func (c *ClientWithResponses) GraphGoalsWithBodyWithResponse(ctx context.Context, params *GraphGoalsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GraphGoalsResponse, error) {
	rsp, err := c.GraphGoalsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGraphGoalsResponse(rsp)
}

func (c *ClientWithResponses) GraphGoalsWithResponse(ctx context.Context, params *GraphGoalsParams, body GraphGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*GraphGoalsResponse, error) {
	rsp, err := c.GraphGoals(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGraphGoalsResponse(rsp)
}

// GraphNeighborsWithBodyWithResponse request with arbitrary body returning *GraphNeighborsResponse
func (c *ClientWithResponses) GraphNeighborsWithBodyWithResponse(ctx context.Context, params *GraphNeighborsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GraphNeighborsResponse, error) {
	rsp, err := c.GraphNeighborsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGraphNeighborsResponse(rsp)
}

func (c *ClientWithResponses) GraphNeighborsWithResponse(ctx context.Context, params *GraphNeighborsParams, body GraphNeighborsJSONRequestBody, reqEditors ...RequestEditorFn) (*GraphNeighborsResponse, error) {
	rsp, err := c.GraphNeighbors(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGraphNeighborsResponse(rsp)
}

// GraphNeighboursWithBodyWithResponse request with arbitrary body returning *GraphNeighboursResponse
func (c *ClientWithResponses) GraphNeighboursWithBodyWithResponse(ctx context.Context, params *GraphNeighboursParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*GraphNeighboursResponse, error) {
	rsp, err := c.GraphNeighboursWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGraphNeighboursResponse(rsp)
}

func (c *ClientWithResponses) GraphNeighboursWithResponse(ctx context.Context, params *GraphNeighboursParams, body GraphNeighboursJSONRequestBody, reqEditors ...RequestEditorFn) (*GraphNeighboursResponse, error) {
	rsp, err := c.GraphNeighbours(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGraphNeighboursResponse(rsp)
}

// ListGoalsWithBodyWithResponse request with arbitrary body returning *ListGoalsResponse
func (c *ClientWithResponses) ListGoalsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ListGoalsResponse, error) {
	rsp, err := c.ListGoalsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListGoalsResponse(rsp)
}

func (c *ClientWithResponses) ListGoalsWithResponse(ctx context.Context, body ListGoalsJSONRequestBody, reqEditors ...RequestEditorFn) (*ListGoalsResponse, error) {
	rsp, err := c.ListGoals(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListGoalsResponse(rsp)
}

// ObjectsWithResponse request returning *ObjectsResponse
func (c *ClientWithResponses) ObjectsWithResponse(ctx context.Context, params *ObjectsParams, reqEditors ...RequestEditorFn) (*ObjectsResponse, error) {
	rsp, err := c.Objects(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseObjectsResponse(rsp)
}

// ParseSetConfigResponse parses an HTTP response from a SetConfigWithResponse call
func ParseSetConfigResponse(rsp *http.Response) (*SetConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSetConsoleResponse parses an HTTP response from a SetConsoleWithResponse call
func ParseSetConsoleResponse(rsp *http.Response) (*SetConsoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetConsoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseConsoleEventsResponse parses an HTTP response from a ConsoleEventsWithResponse call
func ParseConsoleEventsResponse(rsp *http.Response) (*ConsoleEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConsoleEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListDomainClassesResponse parses an HTTP response from a ListDomainClassesWithResponse call
func ParseListDomainClassesResponse(rsp *http.Response) (*ListDomainClassesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDomainClassesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListDomainsResponse parses an HTTP response from a ListDomainsWithResponse call
func ParseListDomainsResponse(rsp *http.Response) (*ListDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Domain
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGraphGoalsResponse parses an HTTP response from a GraphGoalsWithResponse call
func ParseGraphGoalsResponse(rsp *http.Response) (*GraphGoalsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GraphGoalsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Graph
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGraphNeighborsResponse parses an HTTP response from a GraphNeighborsWithResponse call
func ParseGraphNeighborsResponse(rsp *http.Response) (*GraphNeighborsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GraphNeighborsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Graph
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGraphNeighboursResponse parses an HTTP response from a GraphNeighboursWithResponse call
func ParseGraphNeighboursResponse(rsp *http.Response) (*GraphNeighboursResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GraphNeighboursResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Graph
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseListGoalsResponse parses an HTTP response from a ListGoalsWithResponse call
func ParseListGoalsResponse(rsp *http.Response) (*ListGoalsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListGoalsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Node
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseObjectsResponse parses an HTTP response from a ObjectsWithResponse call
func ParseObjectsResponse(rsp *http.Response) (*ObjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ObjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
