// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/korrel8r/client/pkg/swagger/models"
)

// PostGraphsNeighboursReader is a Reader for the PostGraphsNeighbours structure.
type PostGraphsNeighboursReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGraphsNeighboursReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostGraphsNeighboursOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 206:
		result := NewPostGraphsNeighboursPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /graphs/neighbours] PostGraphsNeighbours", response, response.Code())
	}
}

// NewPostGraphsNeighboursOK creates a PostGraphsNeighboursOK with default headers values
func NewPostGraphsNeighboursOK() *PostGraphsNeighboursOK {
	return &PostGraphsNeighboursOK{}
}

/*
PostGraphsNeighboursOK describes a response with status code 200, with default header values.

OK
*/
type PostGraphsNeighboursOK struct {
	Payload *models.Graph
}

// IsSuccess returns true when this post graphs neighbours o k response has a 2xx status code
func (o *PostGraphsNeighboursOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post graphs neighbours o k response has a 3xx status code
func (o *PostGraphsNeighboursOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post graphs neighbours o k response has a 4xx status code
func (o *PostGraphsNeighboursOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post graphs neighbours o k response has a 5xx status code
func (o *PostGraphsNeighboursOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post graphs neighbours o k response a status code equal to that given
func (o *PostGraphsNeighboursOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post graphs neighbours o k response
func (o *PostGraphsNeighboursOK) Code() int {
	return 200
}

func (o *PostGraphsNeighboursOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/neighbours][%d] postGraphsNeighboursOK %s", 200, payload)
}

func (o *PostGraphsNeighboursOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/neighbours][%d] postGraphsNeighboursOK %s", 200, payload)
}

func (o *PostGraphsNeighboursOK) GetPayload() *models.Graph {
	return o.Payload
}

func (o *PostGraphsNeighboursOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Graph)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGraphsNeighboursPartialContent creates a PostGraphsNeighboursPartialContent with default headers values
func NewPostGraphsNeighboursPartialContent() *PostGraphsNeighboursPartialContent {
	return &PostGraphsNeighboursPartialContent{}
}

/*
PostGraphsNeighboursPartialContent describes a response with status code 206, with default header values.

interrupted, partial result
*/
type PostGraphsNeighboursPartialContent struct {
	Payload *models.Graph
}

// IsSuccess returns true when this post graphs neighbours partial content response has a 2xx status code
func (o *PostGraphsNeighboursPartialContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post graphs neighbours partial content response has a 3xx status code
func (o *PostGraphsNeighboursPartialContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post graphs neighbours partial content response has a 4xx status code
func (o *PostGraphsNeighboursPartialContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post graphs neighbours partial content response has a 5xx status code
func (o *PostGraphsNeighboursPartialContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post graphs neighbours partial content response a status code equal to that given
func (o *PostGraphsNeighboursPartialContent) IsCode(code int) bool {
	return code == 206
}

// Code gets the status code for the post graphs neighbours partial content response
func (o *PostGraphsNeighboursPartialContent) Code() int {
	return 206
}

func (o *PostGraphsNeighboursPartialContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/neighbours][%d] postGraphsNeighboursPartialContent %s", 206, payload)
}

func (o *PostGraphsNeighboursPartialContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/neighbours][%d] postGraphsNeighboursPartialContent %s", 206, payload)
}

func (o *PostGraphsNeighboursPartialContent) GetPayload() *models.Graph {
	return o.Payload
}

func (o *PostGraphsNeighboursPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Graph)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
