// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/korrel8r/client/pkg/swagger/models"
)

// PostListsGoalsReader is a Reader for the PostListsGoals structure.
type PostListsGoalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostListsGoalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostListsGoalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /lists/goals] PostListsGoals", response, response.Code())
	}
}

// NewPostListsGoalsOK creates a PostListsGoalsOK with default headers values
func NewPostListsGoalsOK() *PostListsGoalsOK {
	return &PostListsGoalsOK{}
}

/*
PostListsGoalsOK describes a response with status code 200, with default header values.

OK
*/
type PostListsGoalsOK struct {
	Payload []*models.Node
}

// IsSuccess returns true when this post lists goals o k response has a 2xx status code
func (o *PostListsGoalsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post lists goals o k response has a 3xx status code
func (o *PostListsGoalsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post lists goals o k response has a 4xx status code
func (o *PostListsGoalsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post lists goals o k response has a 5xx status code
func (o *PostListsGoalsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post lists goals o k response a status code equal to that given
func (o *PostListsGoalsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post lists goals o k response
func (o *PostListsGoalsOK) Code() int {
	return 200
}

func (o *PostListsGoalsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /lists/goals][%d] postListsGoalsOK %s", 200, payload)
}

func (o *PostListsGoalsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /lists/goals][%d] postListsGoalsOK %s", 200, payload)
}

func (o *PostListsGoalsOK) GetPayload() []*models.Node {
	return o.Payload
}

func (o *PostListsGoalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
