// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/korrel8r/client/pkg/swagger/models"
)

// PostGraphsGoalsReader is a Reader for the PostGraphsGoals structure.
type PostGraphsGoalsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGraphsGoalsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostGraphsGoalsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 206:
		result := NewPostGraphsGoalsPartialContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /graphs/goals] PostGraphsGoals", response, response.Code())
	}
}

// NewPostGraphsGoalsOK creates a PostGraphsGoalsOK with default headers values
func NewPostGraphsGoalsOK() *PostGraphsGoalsOK {
	return &PostGraphsGoalsOK{}
}

/*
PostGraphsGoalsOK describes a response with status code 200, with default header values.

OK
*/
type PostGraphsGoalsOK struct {
	Payload *models.Graph
}

// IsSuccess returns true when this post graphs goals o k response has a 2xx status code
func (o *PostGraphsGoalsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post graphs goals o k response has a 3xx status code
func (o *PostGraphsGoalsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post graphs goals o k response has a 4xx status code
func (o *PostGraphsGoalsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post graphs goals o k response has a 5xx status code
func (o *PostGraphsGoalsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post graphs goals o k response a status code equal to that given
func (o *PostGraphsGoalsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post graphs goals o k response
func (o *PostGraphsGoalsOK) Code() int {
	return 200
}

func (o *PostGraphsGoalsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/goals][%d] postGraphsGoalsOK %s", 200, payload)
}

func (o *PostGraphsGoalsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/goals][%d] postGraphsGoalsOK %s", 200, payload)
}

func (o *PostGraphsGoalsOK) GetPayload() *models.Graph {
	return o.Payload
}

func (o *PostGraphsGoalsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Graph)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGraphsGoalsPartialContent creates a PostGraphsGoalsPartialContent with default headers values
func NewPostGraphsGoalsPartialContent() *PostGraphsGoalsPartialContent {
	return &PostGraphsGoalsPartialContent{}
}

/*
PostGraphsGoalsPartialContent describes a response with status code 206, with default header values.

interrupted, partial result
*/
type PostGraphsGoalsPartialContent struct {
	Payload *models.Graph
}

// IsSuccess returns true when this post graphs goals partial content response has a 2xx status code
func (o *PostGraphsGoalsPartialContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post graphs goals partial content response has a 3xx status code
func (o *PostGraphsGoalsPartialContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post graphs goals partial content response has a 4xx status code
func (o *PostGraphsGoalsPartialContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this post graphs goals partial content response has a 5xx status code
func (o *PostGraphsGoalsPartialContent) IsServerError() bool {
	return false
}

// IsCode returns true when this post graphs goals partial content response a status code equal to that given
func (o *PostGraphsGoalsPartialContent) IsCode(code int) bool {
	return code == 206
}

// Code gets the status code for the post graphs goals partial content response
func (o *PostGraphsGoalsPartialContent) Code() int {
	return 206
}

func (o *PostGraphsGoalsPartialContent) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/goals][%d] postGraphsGoalsPartialContent %s", 206, payload)
}

func (o *PostGraphsGoalsPartialContent) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /graphs/goals][%d] postGraphsGoalsPartialContent %s", 206, payload)
}

func (o *PostGraphsGoalsPartialContent) GetPayload() *models.Graph {
	return o.Payload
}

func (o *PostGraphsGoalsPartialContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Graph)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
